"""change col of table rooms for images

Revision ID: 7cc3da0c32c9
Revises: 8b842c1432b1
Create Date: 2024-10-26 23:32:26.605081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc3da0c32c9'
down_revision: Union[str, None] = '8b842c1432b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image_link', sa.String(), nullable=True))
    op.drop_column('rooms', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'image_link')
    # ### end Alembic commands ###
