"""change col of table hotels for images

Revision ID: 8b842c1432b1
Revises: 478f59b22800
Create Date: 2024-10-26 14:22:54.070808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b842c1432b1'
down_revision: Union[str, None] = '478f59b22800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('image_link', sa.String(), nullable=True))
    op.drop_column('hotels', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'image_link')
    # ### end Alembic commands ###
