"""add booking image

Revision ID: d8ca03938307
Revises: 7cc3da0c32c9
Create Date: 2024-10-30 23:37:57.437618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ca03938307'
down_revision: Union[str, None] = '7cc3da0c32c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'image_link')
    # ### end Alembic commands ###
